# Generated by Django 2.1.7 on 2019-02-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload', models.FileField(upload_to='')),
                ('pub_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='QA_JFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QA_File', models.CharField(max_length=10000)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QusAns.FileUpload')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement_text', models.CharField(max_length=300)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('qa_jfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QusAns.QA_JFile')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QusAns.Statement'),
        ),
    ]
