# Generated by Django 2.1.7 on 2019-02-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement_text', models.CharField(max_length=300)),
                ('pub_datetime', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QusAns.Statement'),
        ),
    ]
