# Generated by Django 2.1.7 on 2019-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QusAns', '0002_qusjsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusjsonfile',
            name='TimeStamp',
            field=models.DateField(auto_now_add=True, verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='pub_datetime',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
