# Generated by Django 2.1.7 on 2019-02-21 12:19

import QusAns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QusAns', '0003_auto_20190221_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusjsonfile',
            name='document',
            field=models.FileField(upload_to=QusAns.models.user_directory_path),
        ),
    ]
