# Generated by Django 2.1.7 on 2019-02-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QusAns', '0005_auto_20190221_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QusJsonFile',
        ),
    ]
